name = input ("enter your name:")
age = input ("enter your age:")
gender = input ("enter your gender")
print ("welcome to you", name)
mark = float(input ("enter your mark:"))
mark = float (input (" enter your mark :"))
num = int (input ("enter your first number :"))
num2 = int (input(" enter your second number :"))
print ("sum=", num + num2)
pan = float (input ("enter the first amount :"))
ping = float (input ("enter the second amount :"))
print ("subtraction=", pan - ping)
push = int (input (" enter the numbers "))
print (type ("push"))